# Generated by Django 3.1.5 on 2021-01-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='expire',
        ),
    ]
