# Generated by Django 3.1.5 on 2021-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='project_todo',
            field=models.IntegerField(default=0),
        ),
    ]
