# Generated by Django 3.1.5 on 2021-06-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_online',
        ),
        migrations.AddField(
            model_name='account',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
