# Generated by Django 3.1.5 on 2021-06-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210605_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='online',
            new_name='is_online',
        ),
    ]
