# Generated by Django 3.1.5 on 2021-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210122_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
