# Generated by Django 3.1.5 on 2021-01-22 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_confirmationcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='exp_date',
            field=models.TimeField(null=True, verbose_name=datetime.date(2021, 1, 22)),
        ),
    ]
