# Generated by Django 3.1.5 on 2021-01-22 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_confirmationcode_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='exp_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.date(2021, 1, 22)),
        ),
    ]
