# Generated by Django 3.1.5 on 2021-01-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210122_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='exp_date',
        ),
    ]
