# Generated by Django 3.1.5 on 2021-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('typist', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.TimeField()),
                ('description', models.TextField()),
                ('number_of_pages', models.IntegerField()),
                ('price_per_page', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('guarantee_price', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
