# Generated by Django 3.1.5 on 2021-06-15 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=project.models.upload_path)),
                ('languages_and_additions', models.TextField()),
                ('number_of_pages', models.IntegerField()),
                ('delivery_deadline', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('IP', 'In Progress'), ('D', 'Done'), ('J', 'Judgment')], default='O', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.IntegerField()),
                ('client_accept', models.DateTimeField(blank=True, null=True)),
                ('typist_ready', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Await'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='A', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('typist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Downloaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
