# Generated by Django 3.1.5 on 2021-03-15 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to=project.models.upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('IP', 'In Progress'), ('DN', 'Done'), ('JM', 'Judgment')], default='OP', max_length=2)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
