# Generated by Django 3.1.5 on 2021-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='delivery_deadline',
            field=models.IntegerField(),
        ),
    ]
