# Generated by Django 3.1.5 on 2021-04-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('A', 'Await'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='A', max_length=3),
        ),
    ]
