# Generated by Django 3.1.5 on 2021-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210526_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='client_accept',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
