# Generated by Django 3.1.5 on 2021-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_offer_client_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='typist_ready',
            field=models.BooleanField(default=False),
        ),
    ]
